/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthFormSection: typeof import('./src/components/AuthFormSection.vue')['default']
    AuthGraphicSection: typeof import('./src/components/AuthGraphicSection.vue')['default']
    CreateEvent: typeof import('./src/components/CreateEvent.vue')['default']
    CreateEventButton: typeof import('./src/components/CreateEventButton.vue')['default']
    DropDownMenu: typeof import('./src/components/DropDownMenu.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventChildren: typeof import('./src/components/EventChildren.vue')['default']
    EventsList: typeof import('./src/components/EventsList.vue')['default']
    ExposeChild: typeof import('./src/components/ExposeChild.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Heirarchy: typeof import('./src/components/Heirarchy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolDetails: typeof import('./src/components/SchoolDetails.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
    SignupForm: typeof import('./src/components/SignupForm.vue')['default']
    SignupFormAddress: typeof import('./src/components/SignupFormAddress.vue')['default']
    SignupFormBasic: typeof import('./src/components/SignupFormBasic.vue')['default']
    SignupFormCredential: typeof import('./src/components/SignupFormCredential.vue')['default']
    SignupFormPersonnel: typeof import('./src/components/SignupFormPersonnel.vue')['default']
    ThemeToggler: typeof import('./src/components/ThemeToggler.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
