/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddressEditForm: typeof import('./src/components/AddressEditForm.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    CreateEventButton: typeof import('./src/components/CreateEventButton.vue')['default']
    CreateEventForm: typeof import('./src/components/CreateEventForm.vue')['default']
    DropDownMenu: typeof import('./src/components/DropDownMenu.vue')['default']
    EditEventForm: typeof import('./src/components/EditEventForm.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventChildren: typeof import('./src/components/EventChildren.vue')['default']
    EventDetails: typeof import('./src/components/EventDetails.vue')['default']
    EventsList: typeof import('./src/components/EventsList.vue')['default']
    ExposeChild: typeof import('./src/components/ExposeChild.vue')['default']
    GoBackButton: typeof import('./src/components/GoBackButton.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Heirarchy: typeof import('./src/components/Heirarchy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconFailure: typeof import('./src/components/icons/IconFailure.vue')['default']
    IconFee: typeof import('./src/components/icons/IconFee.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconLocation: typeof import('./src/components/icons/IconLocation.vue')['default']
    IconSchool: typeof import('./src/components/icons/IconSchool.vue')['default']
    IconSuccess: typeof import('./src/components/icons/IconSuccess.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NoEventsFound: typeof import('./src/components/NoEventsFound.vue')['default']
    PaymentAccountDetails: typeof import('./src/components/PaymentAccountDetails.vue')['default']
    PersonnelEditForm: typeof import('./src/components/PersonnelEditForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchoolDetails: typeof import('./src/components/SchoolDetails.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SignupForm: typeof import('./src/components/SignupForm.vue')['default']
    SignupFormAddress: typeof import('./src/components/SignupFormAddress.vue')['default']
    SignupFormCredential: typeof import('./src/components/SignupFormCredential.vue')['default']
    SignupFormPersonnel: typeof import('./src/components/SignupFormPersonnel.vue')['default']
    ThemeToggler: typeof import('./src/components/ThemeToggler.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TicketCheckout: typeof import('./src/components/TicketCheckout.vue')['default']
    UserEventCard: typeof import('./src/components/UserEventCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
